# Site settings
title: "N Scale Pennsy"
description: "A comparison of N scale rolling stock and locomotives of the Pennsylvania Railroad to their real-life counterparts."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nscalepennsy.uncommonmodels.com" # the base hostname & protocol for your site
initial_publication: 2025
footer_links:
  - title: Uncommon Models
    url: https://www.uncommonmodels.com/

nav_entries:
  - name: Passenger Cars
    url: /passenger/
    subentries:
      - name: Coach Cars
        url: /passenger/coaches.html
      - name: Observation Cars
        url: /passenger/observation.html

  - name: Freight Cars
    url: /freight/
    subentries:
      - name: Boxcars
        url: /freight/boxcars.html
      - name: Cabin Cars
        url: /freight/cabin-cars.html
      - name: Flatcars
        url: /freight/flatcars.html
      - name: Gondolas
        url: /freight/gondolas.html
      - name: Hoppers
        url: /freight/hoppers.html
      - name: Tank Cars
        url: /freight/tank-cars.html

  - name: Motive Power
    url: /motive-power/
    subentries:
      - name: Steam
        url: /motive-power/steam.html
      - name: Electric
        url: /motive-power/electric.html